[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qzvjmsxlmpjm9lyr3el9tyl795nlrynr2tdtn9d39usr29t874j8wk2nys9"]

[[validator_account]]
address = "tnam1q8xtnnmceu5qdzghmxyfa92yxkpw57sdxuvtxmns"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.108.100.31:26656"

[validator_account.consensus_key]
pk = "tpknam1qplpr07l5kthrhhwzl8w8dc5z5y4h8jnw22snqgczr75tlnduezmq703h28"
authorization = "signam1qq55dg98ap4ydgxdl7k33598zxk5stkq5gdn63tm3e2sv595rgx4npl83whxczx4scnqwq6hl7hdw6etecul3zm5vueadssnkr49cwcqcs0n9d"

[validator_account.protocol_key]
pk = "tpknam1qzzrc7e2n4j0p3jq26esljlg8t2nfrc5wl960yugnv06lz6uac0mqnt2jwt"
authorization = "signam1qrjwmmhwjulgmaa3wyq6z03kj44sf7w2rfprjkpkmqevug2jfq06r49ypk7q3drh2yletgasnvryaf86wreuuszak30ayssd2kx9dncd35gyzu"

[validator_account.tendermint_node_key]
pk = "tpknam1qz0np57v6qdt7h3yqr2zknmxsw2h9zhgkrltte4h2qk9cvceyj84uw77ycf"
authorization = "signam1qp5cgsfgeu6n2esytpcgc87z9qez4cf4k6mze4hjpwwm3wjkc2nkcf5svusvljuecjvfx5ghduwsfnpxlgc5say9m96t3m6u0x3tqys9q2qt8s"

[validator_account.eth_hot_key]
pk = "tpknam1qypke7672p4y2eqtauh0ukaqgpfnjzfm5mjfml9crddlgslc2dur8vcn8clxc"
authorization = "signam1q8fyfpn99q8rvzaxc3ullzgf7lflkvrpg39tjaeggj3cmuxzh9ugx9qah00y040uam8cpfwrqyaq4g838nggvwh2zeszmys4wufh6fftqq0dfczd"

[validator_account.eth_cold_key]
pk = "tpknam1qyppnugsqds865qzvqznc2evzsfpd0ylvmqcr9qtgf9t97gw6f497cqnecyl7"
authorization = "signam1q9h07v0dknr3h32rdc3fczahte3yj5zzns23c7y4kue9rphemup4yc7wz7mq3hv6ykpxtwuttyj0v72qnhf0jfrtrzl4f5e4qs0nthayqqt4te30"

[validator_account.metadata]
email = "ruslan.glaznyov@gmail.com"
website = "https://mellifera.network"
discord_handle = "ruslan_mellifera"

[validator_account.signatures]
tpknam1qzvjmsxlmpjm9lyr3el9tyl795nlrynr2tdtn9d39usr29t874j8wk2nys9 = "signam1qp7d9kpuyw98xwq6wa4af6jh07s366l8us4gdjxkdt0mzw2he6ewzzy5y7pgunry77hfqlvgxcknqsk2aks4wuqr000j7v6f08sreks9m39awr"

[[bond]]
source = "tnam1q8xtnnmceu5qdzghmxyfa92yxkpw57sdxuvtxmns"
validator = "tnam1q8xtnnmceu5qdzghmxyfa92yxkpw57sdxuvtxmns"
amount = "1000000"

[bond.signatures]
tpknam1qzvjmsxlmpjm9lyr3el9tyl795nlrynr2tdtn9d39usr29t874j8wk2nys9 = "signam1qz8cw2jj5ppru88wy2p5ufv3f5vr6zyalzxfm2nsa33jgaqtp3pm4u8vvuu7hcs4zz2hv7rc48cujfkrnmr6euwf54d8frvflyvvp7gz22m445"
